on:
  push:
  pull_request:
    paths-ignore:
    - "ga-ignore-**"
env:
  MIRROR_URL: "https://github.com/NoahCherel/chocolatine.git"
  EXECUTABLES: binary1,binary2
jobs:
  check_repository_cleanliness:
    name: check_repository_cleanliness
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v3

  check_program_compilation:
    name: check_program_compilation
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    needs: [check_repository_cleanliness]
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Compile the program
        run: |
          timeout 2m make
      - name: make clean
        run: |
          make clean
  run_tests:
    name: run_tests
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    needs: [check_repository_cleanliness, check_program_compilation]
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          timeout 2m make test_run
  push_to_mirror:
    name: push_to_mirror
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    needs: [check_repository_cleanliness, check_program_compilation, run_tests]
    container:
      image: epitechcontent/epitest-docker
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Push to mirror
        run: |
          timeout 2m make push_to_mirror
