name: Chocolatine
on:
  push:
  pull_request:
    paths-ignore:
    - "ga-ignore-**"
env:
  MIRROR_URL: "https://github.com/NoahCherel/chocolatine.git"
  EXECUTABLES: binary1,binary2
jobs:
  check_repository_cleanliness:
    name: "Check repository cleanliness"
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: "actions/checkout@check_repository_cleanliness"

  check_program_compilation:
    name: "Check_program_compilation"
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    needs: [check_repository_cleanliness]
    steps:
      - name: checkout
        uses: "actions/checkout@check_program_compilation"
      - name: Compile the program
        run: |
          timeout 2m make
      - name: make clean
        run: |
          make clean
  run_tests:
    name: Run tests
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    needs: [check_repository_cleanliness, check_program_compilation]
    steps:
      - name: checkout
        uses: "actions/checkout@run_tests"
      - name: Run tests
        run: |
          timeout 2m make test_run
  push_to_mirror:
    name: Push to mirror
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    needs: [check_repository_cleanliness, check_program_compilation, run_tests]
    steps:
      - name: checkout
        uses: "actions/checkout@push_to_mirror"
      - name: Push to mirror
        run: |
          timeout 2m make push_to_mirror
